# Generated by Django 5.2.3 on 2025-11-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('limit_per_day', models.IntegerField()),
                ('system_prompt', models.TextField()),
                ('research_exp', models.BooleanField(default=False)),
            ],
        ),
    ]
