# Generated by Django 5.2.3 on 2025-11-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisetting',
            name='limit_per_day',
            field=models.IntegerField(default=10),
        ),
    ]
