# Generated by Django 5.2.3 on 2025-11-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authtoken_promptlog_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisetting',
            name='huggingface_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
